### ISSUE TITLE
Bugs Report

### ISSUE THREAD

**Issue by KitrosMC** [NPWorkShop/Exp_Plugin#1]
You can report any Bugs here

**Comment by AP3X3ROS** [comment]
Is there a ALLVIP plugin available can't use plugin without. I translated it all into English aswell

**Comment by KitrosMC** [comment]
Yes, and I will upload it later.And can you tell me how to open a folder on github.I think I cant find the button.

**Comment by AP3X3ROS** [comment]
Open a folder as far as a secret one?
